### ISSUE TITLE
Keep yourself in "ONE FILE".

### ISSUE THREAD

**Issue by HellPie** [jv110/ModPE-PlusPlus_IDE#1]
Learn how to code please and do not disorganize everything in a single class, it would be like cleaning your room by hiding everything under your bed. Then, when you will need to find something under that bed (or to fix a bug in a single class file) I bet you you will prefer to shoot yourself or just recode everything from 0, if the bug is a bit over the "oh it's a typo" kind of bugs.

I highly suggest you learn how to code before you learn how to write code.

http://programmers.stackexchange.com/questions/154228/why-is-it-good-to-split-a-program-into-multiple-classes

**Comment by jv110** [comment]
I know, it was because I had AIDE free at the time, which cant save. I got Prime now.

**Comment by HellPie** [comment]
I suggest, if you are still working on this project, that you at least change the description and move stuff in more classes.
